### ISSUE TITLE
Fails when searching for specific interface by name, which is not present

### ISSUE THREAD

**Issue by mohit-soral** [boneskull/find-external-interface#1]
`findExternalInterface({name:'wlan0'})`

This is when wlan0 is not configured on the system.

Fails with the following error

```
TypeError: Cannot read property 'reduce' of undefined
    at findInAddresses (D:\workspace\node_modules\find-external-interface\index.js:27:21)
    at findExternalInterface (D:\workspace\node_modules\find-external-interface\index.js:37:12)
```

Would have expected it to return 

> null

**Comment by boneskull** [comment]
closed by #2
